#!/bin/bash
#
# Installation instuctions:
#   sudo apt-get install ffmpeg python-scipy
#   sudo apt-get install python-matplotlib (debugging only)
#
# Comments:
#    maurits@vdschee.nl
#

CONVERT="`which ffmpeg ` -v quiet -i"
if [ $? -eq 1 ]; then
  echo "Cannot find 'ffmpeg' executable, is 'ffmpeg' installed?"
  exit -1
fi

if [ $# -eq 0 ]; then
  echo "usage: $0 audio_file.flac"
  exit 0
fi

plot=""

for CURR_FILE in "$@"
do
    if [ "$CURR_FILE" == "--plot" ]; then
	plot="--plot"
	continue
    fi
    $CONVERT "$CURR_FILE" "/tmp/fakeflac_$$.wav"
    if [ -f "/tmp/fakeflac_$$.wav" ]; then
	echo -n "$(basename $0): $CURR_FILE: "  >&2
	if [ $plot != "" ]; then 
	    python3 "$(dirname $BASH_SOURCE)/fakeflac.py" "$plot" "/tmp/fakeflac_$$.wav"
	else
	    python3 "$(dirname $BASH_SOURCE)/fakeflac.py" "/tmp/fakeflac_$$.wav"
	fi
      RESULT=$?
      rm "/tmp/fakeflac_$$.wav"
    fi
done
exit $RESULT
